
package org.tempuri;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Secondvehiclecheck", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/wsdl/Secondvehiclecheck.asmx")
public class Secondvehiclecheck
    extends Service
{
    private static final Logger logger = Logger.getLogger(Secondvehiclecheck.class);
    private final static URL SECONDVEHICLECHECK_WSDL_LOCATION;
    private final static WebServiceException SECONDVEHICLECHECK_EXCEPTION;
    private final static QName SECONDVEHICLECHECK_QNAME = new QName("http://tempuri.org/", "Secondvehiclecheck");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = Secondvehiclecheck.class.getResource("/wsdl/Secondvehiclecheck.asmx");
            //url = new URL("http://202.65.142.140/OTSI2VEHCHK/Secondvehiclecheck.asmx?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
            logger.error("Failed to create URL for the wsdl Location: '/wsdl/Secondvehiclecheck.asmx', retrying as a local file");
            logger.error(ex.getMessage());
        }
        SECONDVEHICLECHECK_WSDL_LOCATION = url;
        SECONDVEHICLECHECK_EXCEPTION = e;
    }

    public Secondvehiclecheck() {
        super(__getWsdlLocation(), SECONDVEHICLECHECK_QNAME);
    }

    public Secondvehiclecheck(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECONDVEHICLECHECK_QNAME, features);
    }

    public Secondvehiclecheck(URL wsdlLocation) {
        super(wsdlLocation, SECONDVEHICLECHECK_QNAME);
    }

    public Secondvehiclecheck(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECONDVEHICLECHECK_QNAME, features);
    }

    public Secondvehiclecheck(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Secondvehiclecheck(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecondvehiclecheckSoap
     */
    @WebEndpoint(name = "SecondvehiclecheckSoap")
    public SecondvehiclecheckSoap getSecondvehiclecheckSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SecondvehiclecheckSoap"), SecondvehiclecheckSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecondvehiclecheckSoap
     */
    @WebEndpoint(name = "SecondvehiclecheckSoap")
    public SecondvehiclecheckSoap getSecondvehiclecheckSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SecondvehiclecheckSoap"), SecondvehiclecheckSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECONDVEHICLECHECK_EXCEPTION!= null) {
            throw SECONDVEHICLECHECK_EXCEPTION;
        }
        return SECONDVEHICLECHECK_WSDL_LOCATION;
    }

}
