
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecondvehiclecheckSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecondvehiclecheckSoap {


    /**
     * 
     * @param strLName
     * @param strFName
     * @param strDOB
     * @param strFHName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetsecondvehiclecheckforotsiDealer", action = "http://tempuri.org/GetsecondvehiclecheckforotsiDealer")
    @WebResult(name = "GetsecondvehiclecheckforotsiDealerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetsecondvehiclecheckforotsiDealer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetsecondvehiclecheckforotsiDealer")
    @ResponseWrapper(localName = "GetsecondvehiclecheckforotsiDealerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetsecondvehiclecheckforotsiDealerResponse")
    public String getsecondvehiclecheckforotsiDealer(
        @WebParam(name = "strFName", targetNamespace = "http://tempuri.org/")
        String strFName,
        @WebParam(name = "strFHName", targetNamespace = "http://tempuri.org/")
        String strFHName,
        @WebParam(name = "strLName", targetNamespace = "http://tempuri.org/")
        String strLName,
        @WebParam(name = "strDOB", targetNamespace = "http://tempuri.org/")
        String strDOB);

}
